import java.lang.*;
import java.io.*;

public class HubConnectGenerator implements Generator {
	private Configuration fConfig;
	private CommandParameter fParam;

	public HubConnectGenerator(Configuration config){
		fConfig = config;
		fParam = CommandParameter.getInstance();
	}

	public void generate(String output) {
		String roles[] = fParam.getRoles();
		int num = roles.length;

		PrintWriter writer = null;
		try {
			FileOutputStream fos = new FileOutputStream(output);
			writer = new PrintWriter(new OutputStreamWriter(fos));
		} catch (FileNotFoundException e) {
			Utility.fatalError("出力ファイル("+output+")を生成できません");
		} catch (SecurityException e) {
			Utility.fatalError("出力ファイル("+output+")を生成できません");
		}

		writer.println("# connect.cfg\n" + 
					   "#  generated by genconfig.jar"); 
		writer.print("#  for ");
		for(int i = 0; i < num; i++) {
			if(i != 0)
				writer.print(", ");
			writer.print(roles[i]);
		}
		writer.println("\t" + num + " robots.\n");
		writer.println("[ERS-210]\n");
		
		for(int i = 0; i < num; i++) {
			writer.println("#Recieves from " + i +
						   ", and sends all robots");
			for(int j = 0; j < num; j++) {
				writer.println("tcpGateway.Receive" + i +
							   "Send" + j + ".CHAR.S" +
							   "\t" +
							   "tcpGateway.Receive" + i +
							   "Send" + j + ".CHAR.O");
			}
			writer.println("");
		}
		
		writer.close();
	}
}
