import java.lang.*;
import java.io.*;

public class HubHostgwGenerator implements Generator {
	private Configuration fConfig;
	private CommandParameter fParam;

	public HubHostgwGenerator(Configuration config) {
		fConfig = config;
		fParam = CommandParameter.getInstance();
	}

	public void generate(String output) {
		String roles[] = fParam.getRoles();
		int num = roles.length;

		NetworkCommand cmd = new NetworkCommand();
		String ips[] = new String[num];
		for(int i = 0; i < num; i++) {
			ips[i] = cmd.getIPAddress(fConfig, roles[i]);
		}
		int portOffset = cmd.getPortOffset(fConfig, roles[0]);

		PrintWriter writer = null;
		try {
			FileOutputStream fos = new FileOutputStream(output);
			writer = new PrintWriter(new OutputStreamWriter(fos));
		} catch (FileNotFoundException e) {
			Utility.fatalError("出力ファイル("+output+")を生成できません");
		} catch (SecurityException e) {
			Utility.fatalError("出力ファイル("+output+")を生成できません");
		}

		writer.println("# AiboHUB HOSTGW.CFG\n" + 
					   "#  generated by genconfig.jar"); 
		writer.print("#  for ");
		for(int i = 0; i < num; i++) {
			if(i != 0)
				writer.print(", ");
			writer.print(roles[i]);
		}
		writer.println("\t" + num + " robots.\n");

		writer.println("# PROXY SERVICE");
		writer.println("! ROBOT_PROXY\t" + (portOffset + 80) + "\t"+ips[0]+"\n");

		writer.println("#Subjects");
		for(int i = 0; i < num; i++) {
			for(int j = 0; j < num; j++) {
				writer.println("tcpGateway.Receive" + i +
							   "Send" + j + ".CHAR.S" +
							   "\t\t" +
							   (portOffset + 40 + j) + "\t" +
							   ips[i]);
			}
			writer.println("");
		}

		writer.println("#Observers");
		for(int i = 0; i < num; i++) {
			for(int j = 0; j < num; j++) {
				writer.println("tcpGateway.Receive" + j +
							   "Send" + i + ".CHAR.O" +
							   "\t\t" +
							   (portOffset + 30 + j) + "\t" +
							   ips[i] + " " +
							   "dmax=8 dmin=1");
			}
			writer.println("");
		}

		writer.close();
	}
}
