# /* LICENSE:
#   =========================================================================
#     CMPack'02 Source Code Release for OPEN-R SDK v1.0
#     Copyright (C) 2002 Multirobot Lab [Project Head: Manuela Veloso]
#     School of Computer Science, Carnegie Mellon University
#   -------------------------------------------------------------------------
#     This software is distributed under the GNU General Public License,
#     version 2.  If you do not have a copy of this licence, visit
#     www.gnu.org, or write: Free Software Foundation, 59 Temple Place,
#     Suite 330 Boston, MA 02111-1307 USA.  This program is distributed
#     in the hope that it will be useful, but WITHOUT ANY WARRANTY,
#     including MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#   -------------------------------------------------------------------------
#     Additionally licensed to Sony Corporation under the following terms:
# 
#     This software is provided by the copyright holders AS IS and any
#     express or implied warranties, including, but not limited to, the
#     implied warranties of merchantability and fitness for a particular
#     purpose are disclaimed.  In no event shall authors be liable for
#     any direct, indirect, incidental, special, exemplary, or consequential
#     damages (including, but not limited to, procurement of substitute
#     goods or services; loss of use, data, or profits; or business
#     interruption) however caused and on any theory of liability, whether
#     in contract, strict liability, or tort (including negligence or
#     otherwise) arising in any way out of the use of this software, even if
#     advised of the possibility of such damage.
#   ========================================================================= */

CC = g++
CFLAGS = -fno-rtti -O2 -g
# CFLAGS = -fno-rtti -O3 -g
# CFLAGS = -fno-rtti -O2 -pg

TARGET = tile
SRC = $(wildcard *.cc)

OBJ = $(SRC:%.cc=%.o)
LIB = 
# -L/usr/X11R6/lib -lX11 -lMagick -lMagick++
# -lpthread

DEF =
# -I/usr/include/X11 -I/usr/include/g++-3/

PREFIX = /bin

.SUFFIXES: .cc
%.o: %.cc $(wildcard *.h)
	$(CC) $(CFLAGS) $(DEF) -c $< -o $@

all: $(TARGET)

install-cygwin: all
	if (uname -s)
	cp -i tile.exe $(PREFIX)/tile.exe

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ) $(LIB)

clean:
	rm -f *.o *~ $(TARGET) core
