#
# Copyright 2003 Sony Corporation 
#
# Permission to use, copy, modify, and redistribute this software is
# hereby granted.
#
# This software is provided "as is" without warranty of any kind,
# either expressed or implied, including but not limited to the
# implied warranties of fitness for a particular purpose.
#

TARGETS=all install clean

.PHONY: $(TARGETS)

$(TARGETS):
	$(MAKE) -C .. $@
